version: "3.9"
services:
  web:
    image: "websterzh/vatprc-queue:latest"
    restart: always
    volumes:
      - ./config:/config
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
    command: redis-server --save 30 1 --loglevel warning --requirepass password
    volumes:
      - ./redis:/data